version: "3.7"

services:
  service.web:
    build: ./services/web
    image: super-smash-heroes/service.web:latest
    labels:
      - traefik.enable=true
      - traefik.http.routers.service-web.rule=Host(`smash.localhost`)
      - traefik.http.services.service-web.loadbalancer.server.port=8080

  service.api-gateway:
    image: traefik:2.1
    ports:
      - 80:80
      - 8000:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./services/api-gateway/traefik.yaml:/etc/traefik/traefik.yaml

  service.superhero:
    build: ./services/superhero
    image: super-smash-heroes/service.superhero:latest
    depends_on:
      db.postgres:
        condition: service_healthy
      db.postgres.init:
        condition: service_completed_successfully
    labels:
      - traefik.enable=true
      - traefik.http.routers.service-superhero.rule=PathPrefix(`/api/superheroes`)
      - traefik.http.routers.service-superhero.middlewares=service-superhero
      - traefik.http.middlewares.service-superhero.replacepathregex.regex=^/api/superheroes(.*)
      - traefik.http.middlewares.service-superhero.replacepathregex.replacement=/v1/superheroes$$1
      - traefik.http.services.service-superhero.loadbalancer.server.port=8080
    environment:
      PORT: 8081
      GATEWAY_PORT: 8080
      DATABASE_URL: postgres://nintendo:nintendo@db.postgres:5432/nintendo?sslmode=disable
      SUPERHERO_API_TOKEN: ${SUPERHERO_API_TOKEN}

  service.battle:
    build: ./services/battle
    image: super-smash-heroes/service.battle:latest
    depends_on:
      db.postgres:
        condition: service_healthy
      db.postgres.init:
        condition: service_completed_successfully
    labels:
      - traefik.enable=true
      - traefik.http.routers.service-battle.rule=PathPrefix(`/api/battle`)
      - traefik.http.routers.service-battle.middlewares=service-battle
      - traefik.http.middlewares.service-battle.replacepathregex.regex=^/api/battle(.*)
      - traefik.http.middlewares.service-battle.replacepathregex.replacement=/v1/battle$$1
      - traefik.http.services.service-battle.loadbalancer.server.port=8080
    environment:
      PORT: 8081
      GATEWAY_PORT: 8080
      DATABASE_URL: postgres://nintendo:nintendo@db.postgres:5432/nintendo?sslmode=disable

  db.postgres:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_DB: nintendo
      POSTGRES_PASSWORD: nintendo
      POSTGRES_USER: nintendo
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
        interval: 5s
        timeout: 5s
        retries: 5
    ports:
      - 5432:5432

  db.postgres.init:
    image: migrate/migrate:v4.16.2
    depends_on:
      db.postgres:
        condition: service_healthy
    entrypoint: ["/run-migrations.sh"]
    environment:
      DATABASE_URL: postgres://nintendo:nintendo@db.postgres:5432/nintendo?sslmode=disable
    volumes:
      - ./databases/postgres/migrations:/migrations
      - ./databases/run-migrations.sh:/run-migrations.sh
