version: "3.7"

services:
  service.superhero:
    build: ./services/superhero
    image: super-smash-heroes/service.superhero:latest
    env_file: ./.env
    environment:
      PORT: 8080
      GATEWAY_PORT: 8081
      POSTGRES_DB: nintendo
      POSTGRES_HOST: db.postgres:5432
      POSTGRES_PASSWORD: nintendo
      POSTGRES_USER: nintendo

  service.battle:
    build: ./services/battle
    image: super-smash-heroes/service.battle:latest
    environment:
      PORT: 8080
      GATEWAY_PORT: 8081
      POSTGRES_DB: nintendo
      POSTGRES_HOST: db.postgres:5432
      POSTGRES_PASSWORD: nintendo
      POSTGRES_USER: nintendo

  db.postgres:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_DB: nintendo
      POSTGRES_PASSWORD: nintendo
      POSTGRES_USER: nintendo
    ports:
      - 5432:5432

  db.postgres.init:
    image: migrate/migrate:v4.10.0
    environment:
      MIGRATIONS_DIR: /postgres/migrations
      POSTGRES_DB: nintendo
      POSTGRES_HOST: db.postgres:5432
      POSTGRES_PASSWORD: nintendo
      POSTGRES_USER: nintendo
    entrypoint:
      - wait-for
      - db.postgres:5432
      - --
      - /postgres/run-migrations.sh
    volumes:
      - ./bin/wait-for:/usr/local/bin/wait-for
      - ./databases/postgres:/postgres
