version: '3.5'

services:
  service.api-gateway:
    image: jaceys/viaduct:latest
    container_name: service.api-gateway
    ports:
      - 8001:80
    volumes:
      - ./config/viaduct.yaml:/config/config.yaml

  service.rest-api:
    image: super-smash-heroes/service.rest-api:latest
    container_name: service.rest-api

  service.superhero:
    image: super-smash-heroes/service.superhero:latest
    container_name: service.superhero
    depends_on:
      - db.superhero
    env_file: .env

  service.battle:
    image: super-smash-heroes/service.battle:latest
    container_name: service.battle
    env_file: .env

  db.superhero:
    image: postgres:11.2-alpine
    container_name: db.superhero
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - ./postgres/migrations:/docker-entrypoint-initdb.d
      # - ./postgres/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
