version: "3.7"

services:
  service.api-gateway:
    image: traefik:2.1
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./services/api-gateway/traefik.yaml:/etc/traefik/traefik.yaml
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.smash.localhost`)
      - traefik.http.routers.traefik.service=api@internal

  service.superhero:
    build: ./services/superhero
    image: super-smash-heroes/service.superhero:latest
    labels:
      - traefik.enable=true
      - traefik.http.routers.service-superhero.rule=Host(`api.smash.localhost`) && PathPrefix(`/superheroes`)
      - traefik.http.routers.service-superhero.middlewares=service-superhero
      - traefik.http.middlewares.service-superhero.replacepathregex.regex=^/superheroes(.*)
      - traefik.http.middlewares.service-superhero.replacepathregex.replacement=/v1/superheroes$$1
      - traefik.http.services.service-superhero.loadbalancer.server.port=8081
    env_file: ./.env
    environment:
      PORT: 8080
      GATEWAY_PORT: 8081
      POSTGRES_DB: nintendo
      POSTGRES_HOST: db.postgres:5432
      POSTGRES_PASSWORD: nintendo
      POSTGRES_USER: nintendo

  service.battle:
    build: ./services/battle
    image: super-smash-heroes/service.battle:latest
    labels:
      - traefik.enable=true
      - traefik.http.routers.service-battle.rule=Host(`api.smash.localhost`) && PathPrefix(`/battle`)
      - traefik.http.routers.service-battle.middlewares=service-battle
      - traefik.http.middlewares.service-battle.replacepathregex.regex=^/battle(.*)
      - traefik.http.middlewares.service-battle.replacepathregex.replacement=/v1/battle$$1
      - traefik.http.services.service-battle.loadbalancer.server.port=8081
    environment:
      PORT: 8080
      GATEWAY_PORT: 8081
      POSTGRES_DB: nintendo
      POSTGRES_HOST: db.postgres:5432
      POSTGRES_PASSWORD: nintendo
      POSTGRES_USER: nintendo

  db.postgres:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_DB: nintendo
      POSTGRES_PASSWORD: nintendo
      POSTGRES_USER: nintendo
    ports:
      - 5432:5432

  db.postgres.init:
    image: migrate/migrate:v4.10.0
    environment:
      MIGRATIONS_DIR: /postgres/migrations
      POSTGRES_DB: nintendo
      POSTGRES_HOST: db.postgres:5432
      POSTGRES_PASSWORD: nintendo
      POSTGRES_USER: nintendo
    entrypoint:
      - wait-for
      - db.postgres:5432
      - --
      - /postgres/run-migrations.sh
    volumes:
      - ./bin/wait-for:/usr/local/bin/wait-for
      - ./databases/postgres:/postgres
