// Code generated by protoc-gen-go. DO NOT EDIT.
// source: superhero.proto

package superhero

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Superhero struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName             string   `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	AlterEgo             string   `protobuf:"bytes,3,opt,name=alter_ego,json=alterEgo,proto3" json:"alter_ego,omitempty"`
	ImageUrl             string   `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Intelligence         int32    `protobuf:"varint,5,opt,name=intelligence,proto3" json:"intelligence,omitempty"`
	Strength             int32    `protobuf:"varint,6,opt,name=strength,proto3" json:"strength,omitempty"`
	Speed                int32    `protobuf:"varint,7,opt,name=speed,proto3" json:"speed,omitempty"`
	Durability           int32    `protobuf:"varint,8,opt,name=durability,proto3" json:"durability,omitempty"`
	Power                int32    `protobuf:"varint,9,opt,name=power,proto3" json:"power,omitempty"`
	Combat               int32    `protobuf:"varint,10,opt,name=combat,proto3" json:"combat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Superhero) Reset()         { *m = Superhero{} }
func (m *Superhero) String() string { return proto.CompactTextString(m) }
func (*Superhero) ProtoMessage()    {}
func (*Superhero) Descriptor() ([]byte, []int) {
	return fileDescriptor_23a1973666112575, []int{0}
}

func (m *Superhero) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Superhero.Unmarshal(m, b)
}
func (m *Superhero) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Superhero.Marshal(b, m, deterministic)
}
func (m *Superhero) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Superhero.Merge(m, src)
}
func (m *Superhero) XXX_Size() int {
	return xxx_messageInfo_Superhero.Size(m)
}
func (m *Superhero) XXX_DiscardUnknown() {
	xxx_messageInfo_Superhero.DiscardUnknown(m)
}

var xxx_messageInfo_Superhero proto.InternalMessageInfo

func (m *Superhero) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Superhero) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *Superhero) GetAlterEgo() string {
	if m != nil {
		return m.AlterEgo
	}
	return ""
}

func (m *Superhero) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

func (m *Superhero) GetIntelligence() int32 {
	if m != nil {
		return m.Intelligence
	}
	return 0
}

func (m *Superhero) GetStrength() int32 {
	if m != nil {
		return m.Strength
	}
	return 0
}

func (m *Superhero) GetSpeed() int32 {
	if m != nil {
		return m.Speed
	}
	return 0
}

func (m *Superhero) GetDurability() int32 {
	if m != nil {
		return m.Durability
	}
	return 0
}

func (m *Superhero) GetPower() int32 {
	if m != nil {
		return m.Power
	}
	return 0
}

func (m *Superhero) GetCombat() int32 {
	if m != nil {
		return m.Combat
	}
	return 0
}

type ListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_23a1973666112575, []int{1}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

type ListResponse struct {
	Superheroes          []*Superhero `protobuf:"bytes,1,rep,name=superheroes,proto3" json:"superheroes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_23a1973666112575, []int{2}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetSuperheroes() []*Superhero {
	if m != nil {
		return m.Superheroes
	}
	return nil
}

type GetRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_23a1973666112575, []int{3}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetResponse struct {
	Superheroes          *Superhero `protobuf:"bytes,1,opt,name=superheroes,proto3" json:"superheroes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_23a1973666112575, []int{4}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetSuperheroes() *Superhero {
	if m != nil {
		return m.Superheroes
	}
	return nil
}

type CreateRequest struct {
	FullName             string   `protobuf:"bytes,1,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	AlterEgo             string   `protobuf:"bytes,2,opt,name=alter_ego,json=alterEgo,proto3" json:"alter_ego,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_23a1973666112575, []int{5}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *CreateRequest) GetAlterEgo() string {
	if m != nil {
		return m.AlterEgo
	}
	return ""
}

type CreateResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_23a1973666112575, []int{6}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_23a1973666112575, []int{7}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_23a1973666112575, []int{8}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Superhero)(nil), "superhero.Superhero")
	proto.RegisterType((*ListRequest)(nil), "superhero.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "superhero.ListResponse")
	proto.RegisterType((*GetRequest)(nil), "superhero.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "superhero.GetResponse")
	proto.RegisterType((*CreateRequest)(nil), "superhero.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "superhero.CreateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "superhero.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "superhero.DeleteResponse")
}

func init() {
	proto.RegisterFile("superhero.proto", fileDescriptor_23a1973666112575)
}

var fileDescriptor_23a1973666112575 = []byte{
	// 491 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x95, 0xdd, 0x26, 0xc4, 0x93, 0x26, 0x2d, 0xab, 0x90, 0x2e, 0x26, 0x82, 0xc8, 0xa7, 0xa8,
	0x87, 0x5a, 0x14, 0x89, 0x03, 0x57, 0x28, 0x15, 0x12, 0x42, 0xc8, 0x15, 0x07, 0xc4, 0x21, 0xda,
	0xc4, 0x83, 0xbb, 0xd2, 0xc6, 0x6b, 0xd6, 0xeb, 0x22, 0x84, 0xb8, 0xf0, 0x0b, 0x48, 0xfc, 0x18,
	0xbf, 0xc0, 0x07, 0xf0, 0x09, 0xc8, 0xbb, 0xb1, 0x63, 0x9b, 0x82, 0x38, 0xce, 0x7b, 0x33, 0x6f,
	0xde, 0xbe, 0xd1, 0xc2, 0x61, 0x5e, 0x64, 0xa8, 0xae, 0x50, 0xc9, 0xd3, 0x4c, 0x49, 0x2d, 0x89,
	0x57, 0x03, 0xfe, 0x2c, 0x91, 0x32, 0x11, 0x18, 0xb2, 0x8c, 0x87, 0x2c, 0x4d, 0xa5, 0x66, 0x9a,
	0xcb, 0x34, 0xb7, 0x8d, 0xc1, 0x77, 0x17, 0xbc, 0xcb, 0xaa, 0x97, 0x8c, 0xc1, 0xe5, 0x31, 0x75,
	0xe6, 0xce, 0xa2, 0x17, 0xb9, 0x3c, 0x26, 0xf7, 0xc0, 0x7b, 0x5f, 0x08, 0xb1, 0x4c, 0xd9, 0x06,
	0xa9, 0x3b, 0x77, 0x16, 0x5e, 0x34, 0x28, 0x81, 0x57, 0x6c, 0x83, 0x25, 0xc9, 0x84, 0x46, 0xb5,
	0xc4, 0x44, 0xd2, 0x3d, 0x4b, 0x1a, 0xe0, 0x3c, 0x91, 0x25, 0xc9, 0x37, 0x2c, 0xc1, 0x65, 0xa1,
	0x04, 0xdd, 0xb7, 0xa4, 0x01, 0xde, 0x28, 0x41, 0x02, 0x38, 0xe0, 0xa9, 0x46, 0x21, 0x78, 0x82,
	0xe9, 0x1a, 0x69, 0xcf, 0x2c, 0x6c, 0x61, 0xc4, 0x87, 0x41, 0xae, 0x15, 0xa6, 0x89, 0xbe, 0xa2,
	0x7d, 0xc3, 0xd7, 0x35, 0x99, 0x40, 0x2f, 0xcf, 0x10, 0x63, 0x7a, 0xcb, 0x10, 0xb6, 0x20, 0xf7,
	0x01, 0xe2, 0x42, 0xb1, 0x15, 0x17, 0x5c, 0x7f, 0xa2, 0x03, 0x43, 0x35, 0x90, 0x72, 0x2a, 0x93,
	0x1f, 0x51, 0x51, 0xcf, 0x4e, 0x99, 0x82, 0x4c, 0xa1, 0xbf, 0x96, 0x9b, 0x15, 0xd3, 0x14, 0x0c,
	0xbc, 0xad, 0x82, 0x11, 0x0c, 0x5f, 0xf2, 0x5c, 0x47, 0xf8, 0xa1, 0xc0, 0x5c, 0x07, 0xcf, 0xe1,
	0xc0, 0x96, 0x79, 0x26, 0xd3, 0x1c, 0xc9, 0x63, 0x18, 0xd6, 0x11, 0x63, 0x4e, 0x9d, 0xf9, 0xde,
	0x62, 0x78, 0x36, 0x39, 0xdd, 0xdd, 0xa1, 0x0e, 0x35, 0x6a, 0x36, 0x06, 0x33, 0x80, 0x0b, 0xac,
	0x54, 0xbb, 0x79, 0x07, 0xe7, 0x30, 0x34, 0xec, 0xdf, 0x96, 0x38, 0xff, 0xb7, 0xe4, 0x05, 0x8c,
	0x9e, 0x2a, 0x64, 0x1a, 0xab, 0x3d, 0xad, 0x3b, 0x3a, 0xff, 0xba, 0xa3, 0xdb, 0xbe, 0x63, 0x30,
	0x87, 0x71, 0x25, 0xb5, 0x35, 0xd5, 0xf5, 0xfc, 0x00, 0x46, 0xcf, 0x50, 0xe0, 0x6e, 0x59, 0xb7,
	0xe1, 0x08, 0xc6, 0x55, 0x83, 0x95, 0x38, 0xfb, 0xe5, 0xc2, 0x51, 0x6d, 0xfd, 0x12, 0xd5, 0x35,
	0x5f, 0x23, 0x79, 0x0d, 0xfb, 0x65, 0xc2, 0x64, 0xda, 0x78, 0x5f, 0xe3, 0x02, 0xfe, 0xf1, 0x1f,
	0xb8, 0x55, 0x0b, 0x8e, 0xbf, 0xfe, 0xf8, 0xf9, 0xcd, 0xbd, 0x4d, 0x0e, 0xc3, 0xeb, 0x87, 0x61,
	0x23, 0x06, 0x12, 0xc1, 0xde, 0x05, 0x6a, 0x72, 0xa7, 0x31, 0xb8, 0xcb, 0xde, 0x9f, 0x76, 0xe1,
	0xad, 0xdc, 0xcc, 0xc8, 0x4d, 0xc9, 0xa4, 0x23, 0x17, 0x7e, 0xe6, 0xf1, 0x17, 0xf2, 0x16, 0xfa,
	0x36, 0x0f, 0x42, 0x1b, 0xf3, 0xad, 0xb4, 0xfd, 0xbb, 0x37, 0x30, 0x5b, 0x71, 0xdf, 0x88, 0x4f,
	0x82, 0xae, 0xd7, 0x27, 0xce, 0x09, 0x79, 0x07, 0x7d, 0x9b, 0x53, 0x4b, 0xba, 0x95, 0x6d, 0x4b,
	0xba, 0x1d, 0x6a, 0xe5, 0xfb, 0xe4, 0x46, 0xdf, 0xab, 0xbe, 0xf9, 0xee, 0x8f, 0x7e, 0x07, 0x00,
	0x00, 0xff, 0xff, 0x9b, 0x2b, 0x4b, 0x47, 0x2a, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SuperheroServiceClient is the client API for SuperheroService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SuperheroServiceClient interface {
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type superheroServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSuperheroServiceClient(cc grpc.ClientConnInterface) SuperheroServiceClient {
	return &superheroServiceClient{cc}
}

func (c *superheroServiceClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/superhero.SuperheroService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *superheroServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/superhero.SuperheroService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *superheroServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/superhero.SuperheroService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *superheroServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/superhero.SuperheroService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SuperheroServiceServer is the server API for SuperheroService service.
type SuperheroServiceServer interface {
	List(context.Context, *ListRequest) (*ListResponse, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
}

// UnimplementedSuperheroServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSuperheroServiceServer struct {
}

func (*UnimplementedSuperheroServiceServer) List(ctx context.Context, req *ListRequest) (*ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedSuperheroServiceServer) Get(ctx context.Context, req *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedSuperheroServiceServer) Create(ctx context.Context, req *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedSuperheroServiceServer) Delete(ctx context.Context, req *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterSuperheroServiceServer(s *grpc.Server, srv SuperheroServiceServer) {
	s.RegisterService(&_SuperheroService_serviceDesc, srv)
}

func _SuperheroService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SuperheroServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/superhero.SuperheroService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SuperheroServiceServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SuperheroService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SuperheroServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/superhero.SuperheroService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SuperheroServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SuperheroService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SuperheroServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/superhero.SuperheroService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SuperheroServiceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SuperheroService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SuperheroServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/superhero.SuperheroService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SuperheroServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SuperheroService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "superhero.SuperheroService",
	HandlerType: (*SuperheroServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _SuperheroService_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _SuperheroService_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _SuperheroService_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _SuperheroService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "superhero.proto",
}
