// Code generated by protoc-gen-go. DO NOT EDIT.
// source: battle.proto

package battle

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Player struct {
	SuperheroId          int32    `protobuf:"varint,1,opt,name=superhero_id,json=superheroId,proto3" json:"superhero_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_88d4c72b5869c382, []int{0}
}

func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (m *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(m, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetSuperheroId() int32 {
	if m != nil {
		return m.SuperheroId
	}
	return 0
}

type GetResultRequest struct {
	PlayerOne            *Player  `protobuf:"bytes,1,opt,name=player_one,json=playerOne,proto3" json:"player_one,omitempty"`
	PlayerTwo            *Player  `protobuf:"bytes,2,opt,name=player_two,json=playerTwo,proto3" json:"player_two,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResultRequest) Reset()         { *m = GetResultRequest{} }
func (m *GetResultRequest) String() string { return proto.CompactTextString(m) }
func (*GetResultRequest) ProtoMessage()    {}
func (*GetResultRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_88d4c72b5869c382, []int{1}
}

func (m *GetResultRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResultRequest.Unmarshal(m, b)
}
func (m *GetResultRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResultRequest.Marshal(b, m, deterministic)
}
func (m *GetResultRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResultRequest.Merge(m, src)
}
func (m *GetResultRequest) XXX_Size() int {
	return xxx_messageInfo_GetResultRequest.Size(m)
}
func (m *GetResultRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResultRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetResultRequest proto.InternalMessageInfo

func (m *GetResultRequest) GetPlayerOne() *Player {
	if m != nil {
		return m.PlayerOne
	}
	return nil
}

func (m *GetResultRequest) GetPlayerTwo() *Player {
	if m != nil {
		return m.PlayerTwo
	}
	return nil
}

type GetResultResponse struct {
	Winner               *Player  `protobuf:"bytes,1,opt,name=winner,proto3" json:"winner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResultResponse) Reset()         { *m = GetResultResponse{} }
func (m *GetResultResponse) String() string { return proto.CompactTextString(m) }
func (*GetResultResponse) ProtoMessage()    {}
func (*GetResultResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_88d4c72b5869c382, []int{2}
}

func (m *GetResultResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResultResponse.Unmarshal(m, b)
}
func (m *GetResultResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResultResponse.Marshal(b, m, deterministic)
}
func (m *GetResultResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResultResponse.Merge(m, src)
}
func (m *GetResultResponse) XXX_Size() int {
	return xxx_messageInfo_GetResultResponse.Size(m)
}
func (m *GetResultResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResultResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResultResponse proto.InternalMessageInfo

func (m *GetResultResponse) GetWinner() *Player {
	if m != nil {
		return m.Winner
	}
	return nil
}

func init() {
	proto.RegisterType((*Player)(nil), "battle.Player")
	proto.RegisterType((*GetResultRequest)(nil), "battle.GetResultRequest")
	proto.RegisterType((*GetResultResponse)(nil), "battle.GetResultResponse")
}

func init() {
	proto.RegisterFile("battle.proto", fileDescriptor_88d4c72b5869c382)
}

var fileDescriptor_88d4c72b5869c382 = []byte{
	// 207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0x4a, 0x2c, 0x29,
	0xc9, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0xb4, 0xb9, 0xd8,
	0x02, 0x72, 0x12, 0x2b, 0x53, 0x8b, 0x84, 0x14, 0xb9, 0x78, 0x8a, 0x4b, 0x0b, 0x52, 0x8b, 0x32,
	0x52, 0x8b, 0xf2, 0xe3, 0x33, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x58, 0x83, 0xb8, 0xe1, 0x62,
	0x9e, 0x29, 0x4a, 0x05, 0x5c, 0x02, 0xee, 0xa9, 0x25, 0x41, 0xa9, 0xc5, 0xa5, 0x39, 0x25, 0x41,
	0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0xba, 0x5c, 0x5c, 0x05, 0x60, 0x03, 0xe2, 0xf3, 0xf3,
	0x52, 0xc1, 0x9a, 0xb8, 0x8d, 0xf8, 0xf4, 0xa0, 0x76, 0x41, 0x8c, 0x0e, 0xe2, 0x84, 0xa8, 0xf0,
	0xcf, 0x4b, 0x45, 0x52, 0x5e, 0x52, 0x9e, 0x2f, 0xc1, 0x84, 0x4f, 0x79, 0x48, 0x79, 0xbe, 0x92,
	0x35, 0x97, 0x20, 0x92, 0x8d, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42, 0x6a, 0x5c, 0x6c, 0xe5,
	0x99, 0x79, 0x79, 0xa9, 0x45, 0x38, 0xac, 0x83, 0xca, 0x1a, 0x05, 0x73, 0xf1, 0x3a, 0x81, 0x25,
	0x82, 0x53, 0x8b, 0xca, 0x32, 0x93, 0x53, 0x85, 0x9c, 0xb8, 0x38, 0xe1, 0xa6, 0x09, 0x49, 0xc0,
	0x74, 0xa1, 0x7b, 0x49, 0x4a, 0x12, 0x8b, 0x0c, 0xc4, 0x6a, 0x25, 0x86, 0x24, 0x36, 0x70, 0xf8,
	0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xd5, 0xe6, 0x24, 0x5a, 0x4f, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BattleServiceClient is the client API for BattleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BattleServiceClient interface {
	GetResult(ctx context.Context, in *GetResultRequest, opts ...grpc.CallOption) (*GetResultResponse, error)
}

type battleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBattleServiceClient(cc grpc.ClientConnInterface) BattleServiceClient {
	return &battleServiceClient{cc}
}

func (c *battleServiceClient) GetResult(ctx context.Context, in *GetResultRequest, opts ...grpc.CallOption) (*GetResultResponse, error) {
	out := new(GetResultResponse)
	err := c.cc.Invoke(ctx, "/battle.BattleService/GetResult", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BattleServiceServer is the server API for BattleService service.
type BattleServiceServer interface {
	GetResult(context.Context, *GetResultRequest) (*GetResultResponse, error)
}

// UnimplementedBattleServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBattleServiceServer struct {
}

func (*UnimplementedBattleServiceServer) GetResult(ctx context.Context, req *GetResultRequest) (*GetResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetResult not implemented")
}

func RegisterBattleServiceServer(s *grpc.Server, srv BattleServiceServer) {
	s.RegisterService(&_BattleService_serviceDesc, srv)
}

func _BattleService_GetResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BattleServiceServer).GetResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/battle.BattleService/GetResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BattleServiceServer).GetResult(ctx, req.(*GetResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BattleService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "battle.BattleService",
	HandlerType: (*BattleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetResult",
			Handler:    _BattleService_GetResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "battle.proto",
}
