---
name: service.battle

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      WORKDIR: ./services/battle
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: "1.21"
    - uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-service.battle-${{ hashFiles('services/battle/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-service.battle-

    - name: Install dependencies
      working-directory: ${{ env.WORKDIR }}
      run: |
        go mod tidy
        git diff --exit-code --name-only
        make tools

    - name: Install protobuf
      run: |
        ./bin/protoinstall
        sudo chmod -R 755 /usr/local/bin/protoc /usr/local/include/google

    - name: Verify protobuf
      working-directory: ${{ env.WORKDIR }}
      run: |
        make proto
        git diff --exit-code --name-only

    - name: Lint
      working-directory: ${{ env.WORKDIR }}
      run: |
        make format
        git diff --exit-code --name-only

    - name: Run tests
      working-directory: ${{ env.WORKDIR }}
      run: make test

    - name: Build
      working-directory: ${{ env.WORKDIR }}
      run: make build
