name: service.superhero

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      WORKDIR: ./services/superhero
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: "1.14"
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-service.superhero-${{ hashFiles('services/superhero/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-service.superhero-
      - name: Setup environment
        run: |
          echo "SUPERHERO_API_TOKEN=${{ secrets.SUPERHERO_API_TOKEN }}" >> .env
      - name: Install protobuf
        run: ./bin/protoinstall protoc go
      - name: Verify protobuf
        working-directory: ${{env.WORKDIR}}
        run: |
          make proto
          if ! git diff --exit-code --name-only; then
            echo "> Generated code not up to date with proto schema"
            exit 1
          fi
      - name: Install dependencies
        working-directory: ${{env.WORKDIR}}
        run: go mod download
      - name: Lint
        working-directory: ${{env.WORKDIR}}
        run: |
          if [[ -n "$(gofmt -l .)" ]]; then
            exit 1
          fi
      - name: Run tests
        working-directory: ${{env.WORKDIR}}
        run: make test
      - name: Build
        working-directory: ${{env.WORKDIR}}
        run: make build
