name: test.integration

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      WORKDIR: ./test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.14"
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-test.integration-${{ hashFiles('test/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-test.integration-
      - name: Setup environment
        run: |
          echo "SUPERHERO_API_TOKEN=${{ secrets.SUPERHERO_API_TOKEN }}" >> .env
      - name: Verify dependencies
        working-directory: ${{ env.WORKDIR }}
        run: |
          go mod tidy
          if ! git diff --exit-code --name-only; then
            echo "> Go modules not tidy"
            exit 1
          fi
      - name: Install dependencies
        working-directory: ${{ env.WORKDIR }}
        run: |
          go mod download
          make tools
      - name: Install protobuf
        run: |
          ./bin/protoinstall
          sudo chmod -R 755 /usr/local/bin/protoc /usr/local/include/google
      - name: Verify protobuf
        working-directory: ${{ env.WORKDIR }}
        run: |
          make proto
          if ! git diff --exit-code --name-only; then
            echo "> Generated code not up to date with proto schema"
            exit 1
          fi
      - name: Lint
        working-directory: ${{ env.WORKDIR }}
        run: |
          if [[ -n "$(gofmt -l .)" ]]; then
            exit 1
          fi
      - name: Build images
        working-directory: ${{ env.WORKDIR }}
        run: make images
      - name: Run integration test suite
        working-directory: ${{ env.WORKDIR }}
        run: make integration
